[package]
name = "caps"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
directories = "6.0.0"
reqwest = "0.13.3"
serde = "1.0.228"
slint = "1.16.1"
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
slint-build = "1.16.1"
